# Generated by Django 3.2.21 on 2023-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
    ]
